### ISSUE TITLE
Officially release Pale Moon for macOS

### ISSUE THREAD

**Issue by SpockFan02** [MoonchildProductions/Pale-Moon#1715]
Pale Moon for macOS is planned to become official. This is a meta-issue for Mac-specific problems and to track what needs to be done/fixed. If anything Mac-specific needs to be fixed before the official release, please mention it here.

OS X 10.7 and higher will be supported.

- Functionality and UX
  - [ ] Intermittent window-dragging problems, possibly theme-dependent, unsure if still present with UXP ([Pale-Moon issue #1598](https://github.com/MoonchildProductions/Pale-Moon/issues/1598))

Pale Moon on macOS functions and is usable and stable.

- Theme
  - [ ] Decide whether or not to revert to old osx theme
  - [X] Lightweight themes (personas)
    - [X] Make sure personas don't kill the titlebar and caption buttons (#491)
    - [x] Missing tab close buttons and dark text with dark lwtheme
  - [X] Private Browsing windows
    - [X] Make sure Private Browsing windows have caption buttons (#584)
    - [X] Make sure [Private Browsing mode is indicated to the user](https://bugzilla.mozilla.org/show_bug.cgi?id=749394)
      - [X] Purple mask indicator (#553) (Missing in fullscreen, [WONTFIX](https://forum.palemoon.org/viewtopic.php?f=41&t=18745#p146861))
  - [X] Ensure expected placement of caption buttons (#586)
    - [x] [Maximized Private browsing windows and maximized windows with lightweight themes have caption buttons and fullscreen arrows shifted up](https://forum.palemoon.org/viewtopic.php?f=41&t=18745#p146861)
  - [X] Unexpected expansion/collapse behavior in bookmark doorhangers (Fixed by MoonchildProductions/UXP#692)

- Release engineering
  - [X] Building and packaging works as expected (There have been issues, e.g. MoonchildProductions/UXP#573)
  - [ ] Decide proper configuration for official builds, and provide wicknix/Mac team access to distribution infrastructure (http://mac.palemoon.org/dist/)
  - [ ] Enable updating and make sure it works
  - [x] Pale Moon needs a space in its name (#701)

This will require testing.

- Documentation
  - [X] Update [wiki page](https://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/macOS), provide sample mozconfig, etc.
  - [ ] mac.palemoon.org
  - [ ] Update information
    - [ ] Project homepage
    - [ ] Roadmap
    - [x] Pale Moon for Mac OSX forum board
    - [ ] etc.

Non-blocking issues:
- Restarting creates a duplicate icon on the dock if the application has been placed there
- Private Browsing windows are not darker-colored
- Private Browsing windows and windows with lightweight themes are missing titles
- ~~Bookmark doorhangers and Properties dropdowns missing button icons~~ (Fixed by MoonchildProductions/UXP#692 and MoonchildProductions/UXP#698)
- [Trackpad swipe history navigation no longer works](https://forum.palemoon.org/viewtopic.php?f=41&t=19796#p147126)
- Lightweight themes cause several windowframe issues.
