### ISSUE TITLE
[Tracking] Permissions manager completion

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#638]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=980050

All of these are available from Page Info, but not from the permissions manager. That should be completed.

- [x] per plugin permissions
- [x] load images for site
- [x] hide mouse pointer
- [x] install add-ons
- [x] show notifications

**Comment by wolfbeast** [comment]
Since evrything was addressed (thanks @janekptacijarabaci !) this is marked solved.
