### ISSUE TITLE
[Meta] Implement downscale during decoding.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#969]
If we want to get rid of the (CPU and memory hungry) HQ downscaling code, and do downscaling during decoding always, we'll have to follow the following plan:

- [X] Make RasterImage support multiple decoders at once (already implemented in Tycho)
- [X] Expose Skia downscaler (HQ downscaler code) to decoders directly (already implemented in Tycho)
- [X] Add DDD to JPG decoder (already implemented in Tycho)
- [ ] Add DDD to BMP decoder
- [ ] Add DDD to ICO decoder
- [ ] Add DDD to ICON decoder
- [ ] Add DDD to PNG decoder
- [ ] Add DDD to GIF decoder
- [ ] Add DDD to WebP decoder
- [ ] Add DDD to JXR decoder
- [ ] Enable DDD for all types
- [ ] Require DDD support for all rasterimages and decoders
- [ ] Remove HQ downscaling code
- [ ] Remove Deoptimization (required for old HQ code)

Individual decoder code hints are linked to dependent bugs to https://bugzilla.mozilla.org/show_bug.cgi?id=1045926

Considering the complexity of this and the pivotal nature of image support to the web, using a feature branch for development is definitely a must, here.

**Comment by wolfbeast** [comment]
feature branch `ddd-work` created -- any PRs for this issue should be made against that branch.

**Comment by rhinoduck** [comment]
So that work won't possibly get duplicated, here is what is in my shop currently:

- DDD in WebP is done, I am waiting for the fate of https://github.com/MoonchildProductions/Pale-Moon/pull/970 so that I can apply appropriate final touches
- DDD in JXR I will be adding as part of the ongoing JXR rewrite https://github.com/MoonchildProductions/Pale-Moon/issues/961

**Comment by wolfbeast** [comment]
#970 is merged in and tested, and merged into the work branch from master, so should be good to go.

**Comment by rhinoduck** [comment]
Thanks!

I pushed https://github.com/rhinoduck/Pale-Moon/commit/59c273d23cd108da5063b42c11114287d9b29625 where you can see the current state of the WebP decoder (link might die to a force push eventually); looking at it is not necessary unless you're curious .

There's a "tiny" problem that nothing seems to get rendered from the downscale decode (at least for the first pass, and at least for images larger than the content area size); the JPEG decoder behaves the same for me though, so this looks like a deeper issue. I still need to verify the details of this; anyway, that's what's next.

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.
